#!/usr/bin/php
<?php

    require_once 'Validate.php';
    $validate = new Validate($argv, $argc);
    if ($validate->isEverythingOK()) {
        $issueDetails = $validate->_parseDetails();
        switch ($issueDetails->vendorName) {
            case 'bitbucket.org':
                require_once 'CreateBitbucketIssue.php';
                $issueHandle = new CreateBitbucketIssue($issueDetails);
                break;
            case 'api.github.com':
                require_once 'CreateGithubIssue.php';
                $issueHandle = new CreateGithubIssue($issueDetails);
                break;
            default:
                die("\nService adapter not specified.\n");
        }

        try {
            $issueHandle->createIssue();
        } catch (WebServiceException $wse) {
            die($wse->getMessage());
        }
    }
